name: Racket

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: [ 'BC', 'CS' ]
        racket-version: [ '8.0', '8.1' ]
    steps:
    - uses: actions/checkout@master
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/.racket
        key: ${{ runner.os }}-primes
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.4
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - run: raco pkg install --auto
    - run: make test
